<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />




<title>Using mosaic’s favstats()</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cosmo.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<link href="site_libs/font-awesome-4.5.0/css/font-awesome.min.css" rel="stylesheet" />

<style type="text/css">code{white-space: pre;}</style>
<link rel="stylesheet"
      href="site_libs/highlight/textmate.css"
      type="text/css" />
<script src="site_libs/highlight/highlight.js"></script>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs && document.readyState && document.readyState === "complete") {
   window.setTimeout(function() {
      hljs.initHighlighting();
   }, 0);
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>

<link rel="stylesheet" href="styles.css" type="text/css" />

</head>

<body>

<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
  height: auto;
}
.tabbed-pane {
  padding-top: 12px;
}
button.code-folding-btn:focus {
  outline: none;
}
</style>

<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 51px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 56px;
  margin-top: -56px;
}

.section h2 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h3 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h4 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h5 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h6 {
  padding-top: 56px;
  margin-top: -56px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>


<div class="container-fluid main-container">

<!-- tabsets -->
<script src="site_libs/navigation-1.0/tabsets.js"></script>
<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});
</script>

<!-- code folding -->




<script>
$(document).ready(function ()  {

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\/?&!#<>]/g, '').replace(/\s/g, '_').toLowerCase();
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = false;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.9em;
  padding-left: 5px;
}

.tocify .list-group-item {
  border-radius: 0px;
}

.tocify-subheader {
  display: inline;
}
.tocify-subheader .tocify-item {
  font-size: 0.95em;
  padding-left: 10px;
}

</style>

<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row-fluid">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-inverse  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">tigerstats</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li>
  <a href="about.html">About</a>
</li>
<li>
  <a href="instructorNotes.html">Instructors</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Vignettes
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li class="dropdown-header">Outlines</li>
    <li>
      <a href="R_Descriptive.html">Descriptive Outline</a>
    </li>
    <li>
      <a href="R_Inferential.html">Inferential Outline</a>
    </li>
    <li class="dropdown-header">Graphics</li>
    <li>
      <a href="barchartGC.html">Bar Charts</a>
    </li>
    <li>
      <a href="bwplot.html">Box-and-Whisker Plots</a>
    </li>
    <li>
      <a href="densityplot.html">Density Plots</a>
    </li>
    <li>
      <a href="histogram.html">Histograms</a>
    </li>
    <li class="dropdown-header">Numerical Summaries</li>
    <li>
      <a href="favstats.html">Mosaic's Favstats</a>
    </li>
    <li>
      <a href="xtabs.html">Cross-tables and Percentages</a>
    </li>
    <li class="dropdown-header">Linear Mpdels</li>
    <li>
      <a href="lmGC.html">lmGC</a>
    </li>
    <li>
      <a href="polyfitGC.html">polyfitGC</a>
    </li>
    <li class="dropdown-header">Probability</li>
    <li>
      <a href="pbinomGC.html">pbinomGC</a>
    </li>
    <li>
      <a href="pnormGC.html">pnormGC</a>
    </li>
    <li>
      <a href="qnorm.html">qnorm</a>
    </li>
    <li>
      <a href="qnormGC.html">qnormGC</a>
    </li>
    <li class="dropdown-header">Inferential Procedures</li>
    <li>
      <a href="binomtestGC.html">binomtestGC</a>
    </li>
    <li>
      <a href="proptestGC.html">proptestGC</a>
    </li>
    <li>
      <a href="chisqtestGC.html">The Chi-Square Test</a>
    </li>
    <li>
      <a href="ttestGC.html">The t-Test</a>
    </li>
  </ul>
</li>
<li>
  <a href="resources.html">Related</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="https://github.com/homerhanumat/tigerstats">
    <span class="fa fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">



<h1 class="title toc-ignore">Using mosaic’s favstats()</h1>

</div>


<div id="preliminaries" class="section level1">
<h1>Preliminaries</h1>
<p><code>favstats()</code> comes from the <code>mosaic</code> package and we will use some data from the <code>tigerstats</code> package, so make sure that both are loaded:</p>
<pre class="r"><code>require(mosaic)
require(tigerstats)</code></pre>
<p>In this tutorial we will work with the <code>m111survey</code> data frame from <code>tigerstats</code> package. If you are not yet familiar with this data, then run:</p>
<pre class="r"><code>data(m111survey)
View(m111survey)
help(m111survey)</code></pre>
<p>Remember that you can also learn about the types of each variable in the data frame with the <code>str()</code> function:</p>
<pre class="r"><code>str(m111survey)</code></pre>
<pre><code>## &#39;data.frame&#39;:    71 obs. of  12 variables:
##  $ height         : num  76 74 64 62 72 70.8 70 79 59 67 ...
##  $ ideal_ht       : num  78 76 NA 65 72 NA 72 76 61 67 ...
##  $ sleep          : num  9.5 7 9 7 8 10 4 6 7 7 ...
##  $ fastest        : int  119 110 85 100 95 100 85 160 90 90 ...
##  $ weight_feel    : Factor w/ 3 levels &quot;1_underweight&quot;,..: 1 2 2 1 1 3 2 2 2 3 ...
##  $ love_first     : Factor w/ 2 levels &quot;no&quot;,&quot;yes&quot;: 1 1 1 1 1 1 1 1 1 1 ...
##  $ extra_life     : Factor w/ 2 levels &quot;no&quot;,&quot;yes&quot;: 2 2 1 1 2 1 2 2 2 1 ...
##  $ seat           : Factor w/ 3 levels &quot;1_front&quot;,&quot;2_middle&quot;,..: 1 2 2 1 3 1 1 3 3 2 ...
##  $ GPA            : num  3.56 2.5 3.8 3.5 3.2 3.1 3.68 2.7 2.8 NA ...
##  $ enough_Sleep   : Factor w/ 2 levels &quot;no&quot;,&quot;yes&quot;: 1 1 1 1 1 2 1 2 1 2 ...
##  $ sex            : Factor w/ 2 levels &quot;female&quot;,&quot;male&quot;: 2 2 1 1 2 2 2 2 1 1 ...
##  $ diff.ideal.act.: num  2 2 NA 3 0 NA 2 -3 2 0 ...</code></pre>
</div>
<div id="studying-one-numerical-variable" class="section level1">
<h1>Studying One Numerical Variable</h1>
<p>“favstats” is short for “favorite statistics”: it will give you the some of the most popular summary statistics for numerical variables.</p>
<p>Suppose, for example, that you want to know how fast people in the <code>m111survey</code> sample tend to drive, when they drive their fastest. The you want to study the numerical variable <strong>fastest</strong>: the fastest speed each person claims to have ever driven, measured in miles per hour. Just try <code>favstats()</code> with the usual formula-data input:</p>
<pre class="r"><code>favstats(~fastest, data = m111survey)</code></pre>
<pre><code>##  min   Q1 median    Q3 max     mean      sd  n missing
##   60 90.5    102 119.5 190 105.9014 20.8773 71       0</code></pre>
<p>Remember what each of the statistics tells you:</p>
<ul>
<li>The minimum fastest speed drive by anyone in the survery was 60 mph.</li>
<li>The maximum fastest speed was 190 mph.</li>
<li>About 25% of the survey participants drove less than 90.5 mph (the First Quartile)</li>
<li>About 75% percent of the survey participants drove less than 119.5 mph (the Third Quartile)</li>
<li>About 50% of the participants drove less than 102 mph (the median)</li>
<li>The mean speed for this sample of students was about 105.9 mph …</li>
<li>… give or take about 20.9 mph or so (the standard deviation).</li>
</ul>
<p>We also see that</p>
<ul>
<li>71 people answered the question about fastest speed;</li>
<li>Nobody did not answer (missing = 0).</li>
</ul>
</div>
<div id="studying-the-relationship-between-a-numerical-variable-and-a-factor-variable" class="section level1">
<h1>Studying the Relationship Between a Numerical Variable and a Factor Variable</h1>
<p>Studying the relationship between a numerical variable and factor variable involves what is popularly known as “breaking the data into groups” based on the values of the factor variable. More formally, we obtain the conditional distributions of the numerical variable given the various possible values of the factor variable, and look for difference between these distributions. If we see large differences. then we know that the factor variable “makes a difference” in the likely values of the numerical variable, i.e., the two variable are related.</p>
<p>For example we might want to know if the fastest speed one drives might be related to one’s sex. The relevant variables in <code>m111survey</code> are then the numerical <strong>fastest</strong> and the factor variable <strong>sex</strong>.</p>
<p>In formula-data input for <code>favstats()</code> the formula always follows the format:</p>
<p><span class="math display">\[numerical \sim factor.\]</span></p>
<p>So we run the following command:</p>
<pre class="r"><code>favstats(fastest~sex, data = m111survey)</code></pre>
<pre><code>##      sex min Q1 median    Q3 max     mean       sd  n missing
## 1 female  60 90     95 110.0 145 100.0500 17.60966 40       0
## 2   male  85 99    110 122.5 190 113.4516 22.56818 31       0</code></pre>
<p>The first row of the output gives a summary of the conditional distribution of <strong>fastest</strong>, given that <strong>sex</strong> is female.</p>
<p>The second row summarizes the conditional distribution of <strong>fastest</strong>, given that <strong>sex</strong> is male.</p>
<p>The two conditional distribution are not the same. For example, we see that on average females drove about 100 mph, whereas the guys drove about 113.4 mph. The guys appear to drive faster than the gals: for this sample of students, fastest speed drive does indeed appear to be related to sex.</p>
</div>
<div id="limiting-the-output" class="section level1">
<h1>Limiting the Output</h1>
<p>Sometimes you want just a few of the numbers from <code>favstats()</code>. If you would like to display only those numbers you can do so using brackets “[&quot; and “]”, along with a list of the names of the columns you want to see. For example, to display only the means and the standard deviations for <strong>fastest</strong>, ask for:</p>
<pre class="r"><code>favstats(~fastest, data=m111survey)[c(&quot;mean&quot;,&quot;sd&quot;)]</code></pre>
<pre><code>##      mean      sd
##  105.9014 20.8773</code></pre>
<p>The brackets are R’s way of locating particular parts of an object. If you want to display more than one column, make sure to combine their names (in quotes) in a list with the <code>c()</code> function, as shown above.</p>
<p>When you are breaking a numerical variable into groups, you will probably also want to see the group names: this requires the addition of the column named for the factor variable in question. Therefore, to see just the mean and the standard deviation for <strong>fastest</strong> broken down by <strong>sex</strong>, ask for:</p>
<pre class="r"><code>favstats(fastest~sex, data = m111survey)[c(&quot;sex&quot;,&quot;mean&quot;,&quot;sd&quot;)]</code></pre>
<pre><code>##      sex     mean       sd
## 1 female 100.0500 17.60966
## 2   male 113.4516 22.56818</code></pre>
</div>
<div id="warning" class="section level1">
<h1>Warning</h1>
<p><code>favstats()</code> specializes in numerical variables: it does not like being used to study a factor variable by itself. Look what happens if you try to use it to study the factor variable <strong>sex</strong>:</p>
<pre class="r"><code>favstats(~sex, data = m111survey)</code></pre>
<pre><code>## Warning in FUN(eval(formula[[2]], data, .envir), ...): Auto-converting
## factor to numeric.</code></pre>
<pre><code>##  min Q1 median Q3 max    mean        sd  n missing
##    1  1      1  2   2 1.43662 0.4994967 71       0</code></pre>
<p><code>favstats()</code> converted the factor variable to a numeric variable and tried to give you some useful information based on that conversion, but elements of the output (especially the mean and the standard deviation) are meaningless in the context of factor variables. In order to study a factor variable you really should look instead at functions like <code>xtabs()</code>.</p>
</div>



<!-- bizible -->
<script type="text/javascript" src="//cdn.bizible.com/scripts/bizible.js" async=""></script>


<!-- disqus -->
<!--  <div id="disqus_thread" style="margin-top: 45px;"></div>
    <script type="text/javascript">
        /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
        var disqus_shortname = 'rmarkdown'; // required: replace example with your forum shortname

        /* * * DON'T EDIT BELOW THIS LINE * * */
        (function() {
            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
            dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
            (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
        })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
    <a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>

-->


</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
$(document).ready(function () {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
});

</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
