<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />




<title>Using lmGC(), predict() and plot()</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cosmo.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<link href="site_libs/font-awesome-4.5.0/css/font-awesome.min.css" rel="stylesheet" />

<style type="text/css">code{white-space: pre;}</style>
<link rel="stylesheet"
      href="site_libs/highlight/textmate.css"
      type="text/css" />
<script src="site_libs/highlight/highlight.js"></script>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs && document.readyState && document.readyState === "complete") {
   window.setTimeout(function() {
      hljs.initHighlighting();
   }, 0);
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>

<link rel="stylesheet" href="styles.css" type="text/css" />

</head>

<body>

<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
  height: auto;
}
.tabbed-pane {
  padding-top: 12px;
}
button.code-folding-btn:focus {
  outline: none;
}
</style>

<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 51px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 56px;
  margin-top: -56px;
}

.section h2 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h3 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h4 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h5 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h6 {
  padding-top: 56px;
  margin-top: -56px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>


<div class="container-fluid main-container">

<!-- tabsets -->
<script src="site_libs/navigation-1.0/tabsets.js"></script>
<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});
</script>

<!-- code folding -->




<script>
$(document).ready(function ()  {

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\/?&!#<>]/g, '').replace(/\s/g, '_').toLowerCase();
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = false;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.9em;
  padding-left: 5px;
}

.tocify .list-group-item {
  border-radius: 0px;
}

.tocify-subheader {
  display: inline;
}
.tocify-subheader .tocify-item {
  font-size: 0.95em;
  padding-left: 10px;
}

</style>

<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row-fluid">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-inverse  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">tigerstats</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li>
  <a href="about.html">About</a>
</li>
<li>
  <a href="instructorNotes.html">For Instructors</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Vignettes
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li class="dropdown-header">Outlines</li>
    <li>
      <a href="R_Descriptive.html">Descriptive Outline</a>
    </li>
    <li>
      <a href="R_Inferential.html">Inferential Outline</a>
    </li>
    <li class="dropdown-header">Graphics</li>
    <li>
      <a href="barchartGC.html">Bar Charts</a>
    </li>
    <li>
      <a href="bwplot.html">Box-and-Whisker Plots</a>
    </li>
    <li>
      <a href="densityplot.html">Density Plots</a>
    </li>
    <li>
      <a href="histogram.html">Histograms</a>
    </li>
    <li class="dropdown-header">Numerical Summaries</li>
    <li>
      <a href="favstats.html">Mosaic's Favstats</a>
    </li>
    <li>
      <a href="xtabs.html">Cross-tables and Percentages</a>
    </li>
    <li class="dropdown-header">Linear Mpdels</li>
    <li>
      <a href="lmGC.html">lmGC</a>
    </li>
    <li>
      <a href="polyfitGC.html">polyfitGC</a>
    </li>
    <li class="dropdown-header">Probability</li>
    <li>
      <a href="pbinomGC.html">pbinomGC</a>
    </li>
    <li>
      <a href="pnormGC.html">pnormGC</a>
    </li>
    <li>
      <a href="qnorm.html">qnorm</a>
    </li>
    <li>
      <a href="qnormGC.html">qnormGC</a>
    </li>
    <li class="dropdown-header">Inferential Procedures</li>
    <li>
      <a href="binomtestGC.html">binomtestGC</a>
    </li>
    <li>
      <a href="proptestGC.html">proptestGC</a>
    </li>
    <li>
      <a href="chisqtestGC.html">The Chi-Square Test</a>
    </li>
    <li>
      <a href="ttestGC.html">The t-Test</a>
    </li>
  </ul>
</li>
<li>
  <a href="resources.html">Related</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="https://github.com/homerhanumat/tigerstats">
    <span class="fa fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">



<h1 class="title toc-ignore">Using lmGC(), predict() and plot()</h1>

</div>


<div id="preliminaries" class="section level1">
<h1>Preliminaries</h1>
<p>The function <code>lmGC()</code> is a starter-tool for simple linear regression, when you are studying the relationship between two numerical variables, one of which you consider to be an explanatory or predictor variable and the other of which you think of as the response. It’s only a starter-tool: by the end of the course, or in later statistics courses, you will move on to R’s function <code>lm()</code>, which allows you to work with more than one explanatory variable and which provides additional useful information in its output. Also, in <code>lm()</code> the explanatory variable(s) can even be factors!</p>
<p>The function (and some of the data) that we will use comes from the <code>tigerstats</code> package, so make sure that it is loaded:</p>
<pre class="r"><code>require(tigerstats)</code></pre>
<p>In this tutorial we will work with a couple of data sets: <code>mtcars</code> from the <code>data</code> package that comes with the basic R installation,<code>fuel</code> from the <code>tigerstats</code> package and <code>RailTrail</code> from the package <code>mosaicData</code>, so make sure you become familiar with them. The following commands may be helpful in this regard:</p>
<pre class="r"><code>data(mtcars)
View(mtcars)
help(mtcars)</code></pre>
<p>For <code>fuel</code>:</p>
<pre class="r"><code>data(fuel)
View(fuel)
help(fuel)</code></pre>
<p>For <code>RailTrail</code>:</p>
<pre class="r"><code>require(mosaicData)
data(RailTrail)
View(RailTrail)
help(RailTrail)</code></pre>
</div>
<div id="formula-data-input" class="section level1">
<h1>Formula-Data Input</h1>
<p>Like many R functions, <code>lmGC()</code> accepts formula-data input. The general command looks like:</p>
<p><span class="math display">\[lmGC(response \sim explanatory, data = DataFrame)\]</span></p>
<p>If you are interested in studying the relationship between the fuel efficiency of a car (<strong>mpg</strong> in the <code>mtcars</code> data frame, measured in miles per gallon) and its weight (<strong>wt</strong> in <code>mtcars</code>, measured in thousands of pounds), then you can run:</p>
<pre class="r"><code>lmGC(mpg ~ wt, data = mtcars)</code></pre>
<pre><code>## 
##  Linear Regression
## 
## Correlation coefficient r =  -0.8677 
## 
## Equation of Regression Line:
## 
##   mpg = 37.2851 + -5.3445 * wt 
## 
## Residual Standard Error: s   = 3.0459 
## R^2 (unadjusted):        R^2 = 0.7528</code></pre>
<p>The output to the console is rather minimal. You get:</p>
<ul>
<li>the correlation coefficient <span class="math inline">\(r\)</span>. We need to look at a scatter plot to be really sure about it (for plots, see below), but at this point the value <span class="math inline">\(r = -0.87\)</span> indicates a fairly strong negative linear relationship between fuel efficiency and weight.</li>
<li>the equation of the regression line. From the slope of -5.34, we see that for every thousand pound increase in the weight of a car, we predict a 5.34 mpg decrease in the fuel efficiency.</li>
<li>the residual standard error <span class="math inline">\(s\)</span>. As a rough rule of thumb, we figure that when we use the regression equation to predict the fuel efficiency of a car from its weight, that prediction is liable to be off by about <span class="math inline">\(s\)</span> miles per gallon, or so.</li>
<li>the unadjusted <span class="math inline">\(R^2\)</span>. We see here that about 75% of the variation in the fuel efficiency of the cars in the data set is accounted for by the variation in their weights. since <span class="math inline">\(R^2\)</span> is fairly high, it seems that weight is a fairly decent predictor of fuel efficiency.</li>
</ul>
</div>
<div id="prediction" class="section level1">
<h1>Prediction</h1>
<p>When the value of the explanatory variable for an individual is known and you wish to predict the value of the response variable for that individual, you can use the <code>predict()</code> function. Its arguments are the linear model that is created by <code>lmGC()</code>, and the value <code>x</code> of the explanatory variable.</p>
<p>If you think that you might want to use <code>predict()</code>, you may first want to store the model in a variable, for example:</p>
<pre class="r"><code>WeightEff &lt;- lmGC(mpg ~ wt, data = mtcars)</code></pre>
<p>Then if you want to predict the fuel efficiency of a car that weights 3000 pounds, run this command:</p>
<pre class="r"><code>predict(WeightEff, x = 3)</code></pre>
<pre><code>## Predict mpg is about 21.25,
## give or take 3.095 or so for chance variation.</code></pre>
<p>We predict that a 3000 pound car (from the time of the Motor Trend study that produced this data) would have a fuel efficiency of 21.25 mpg, give or take about 3.095 mpg or so. The “give-or-take” figure here is known as the <em>prediction standard error</em>. It’s a little bit bigger than the residual standard error <span class="math inline">\(s\)</span>, and as a give-or-take figure it’s a bit more reliable. (By the way, it also differs for different values of the explanatory variable.)</p>
<p>You can also get a <em>prediction interval</em> for the response variable if you use the <code>level</code> argument:</p>
<pre class="r"><code>predict(WeightEff,x=3,level=0.95)</code></pre>
<pre><code>## Predict mpg is about 21.25,
## give or take 3.095 or so for chance variation.
## 
## 95%-prediction interval:
##           lower.bound         upper.bound          
##           14.929874           27.573549</code></pre>
<p>The interval says you can be about 95% confident that the actual efficiency of the car is somewhere between 14.9 and 27.6 miles per gallon.</p>
</div>
<div id="plotting" class="section level1">
<h1>Plotting</h1>
<p>But we are getting ahead of ourselves! In order to use linear models at all, we need to make sure that our data really do show a linear relationship. The single best way to check this is to look at a scatter-plot, so <code>lmGC()</code> comes equipped with a option to produce one: just set the argument <code>graph</code> to <code>TRUE</code>, as follows:</p>
<pre class="r"><code>lmGC(mpg ~ wt, data = mtcars, graph = TRUE)</code></pre>
<pre><code>## 
##  Linear Regression
## 
## Correlation coefficient r =  -0.8677 
## 
## Equation of Regression Line:
## 
##   mpg = 37.2851 + -5.3445 * wt 
## 
## Residual Standard Error: s   = 3.0459 
## R^2 (unadjusted):        R^2 = 0.7528</code></pre>
<p><img src="lmGC_files/figure-html/unnamed-chunk-10-1.png" width="528" /></p>
<p>The scatter-plot includes the regression line. Indeed, the cloud of point seems to follow a line fairly well. The relationship may be thought of as linear, so using <code>lmGC()</code> for tasks like prediction does make sense, for this data.</p>
<p>You can also perform some simple diagnostics using the <code>plot()</code> function:</p>
<pre class="r"><code>plot(WeightEff)</code></pre>
<p><img src="lmGC_files/figure-html/unnamed-chunk-11-1.png" width="432" /></p>
<p>You get two graphs:</p>
<ul>
<li>a density plot of the residuals. If the distribution of the residuals is roughly bell-shaped, then the 68-95 Rule says that:
<ul>
<li>about 68% of the residuals are between <span class="math inline">\(-s\)</span> and <span class="math inline">\(s\)</span>;</li>
<li>about 95% of the residuals are between <span class="math inline">\(-2s\)</span> and <span class="math inline">\(2s\)</span>.</li>
</ul></li>
<li>A plot of the residuals vs, the <code>fitted</code> <span class="math inline">\(y\)</span>-values (the <span class="math inline">\(y\)</span>-coordinates of the points on the original scatter-plot). If the points exhibit a linear relationship with about the same amount of scatter all the way along the regression line, then this plot will look like a random cloud of points</li>
</ul>
<p>If you plan to use your regression line for prediction and to rely upon the prediction standard errors and prediction intervals provided by the <code>predict()</code> function, then the residuals should be roughly bell-shaped, and the plot of residuals vs. fits should look pretty much like a random cloud.</p>
<p>In this case, the plots indicate that we can make reliable predictions from our linear model.</p>
<p>On the other hand, consider <code>fuel</code> data frame, which shows the results of a study where a British Ford Escort was driven at various speed along a standard course, and the fuel efficiency (in kilometers traveled per liter of fuel consumed) was recorded at each speed. Let’s try a linear model with <strong>speed</strong> as explanatory and <strong>efficiency</strong> as the response, with some diagnostic plots attached:</p>
<pre class="r"><code>effSpeed &lt;- lmGC(efficiency ~ speed, data = fuel)
plot(effSpeed)</code></pre>
<p><img src="lmGC_files/figure-html/unnamed-chunk-12-1.png" width="432" /></p>
<p>The residuals have a roughly-bell-shaped distribution, but the residual plot is clearly patterned. Something is amiss! Let’s look at a scatter-plot of the data:</p>
<pre class="r"><code>xyplot(efficiency~speed,data=fuel,
        xlab=&quot;speed (kilometers/hour&quot;,
        ylab=&quot;fuel effiency (liters/100km&quot;,
        pch=19,col=&quot;blue&quot;,type=c(&quot;p&quot;,&quot;r&quot;),
        main=&quot;Speed and Fuel Efficiency\nfor a British Ford Escort&quot;)</code></pre>
<p><img src="lmGC_files/figure-html/unnamed-chunk-13-1.png" width="528" /></p>
<p>The relationship is strongly curvilinear: it makes no sense to use the regression line (shown in the plot above) to study the relationship between these two variables!</p>
</div>
<div id="further-checks" class="section level1">
<h1>Further Checks</h1>
<p>Another nice way to check whether your fit is appropriate to the data is to use the <code>check</code> argument for <code>lmGC()</code>. Let’s perform a check on the <code>WeightEff</code> model:</p>
<pre class="r"><code>lmGC(mpg ~ wt, data = mtcars, check = TRUE)</code></pre>
<pre><code>## 
##  Linear Regression
## 
## Correlation coefficient r =  -0.8677 
## 
## Equation of Regression Line:
## 
##   mpg = 37.2851 + -5.3445 * wt 
## 
## Residual Standard Error: s   = 3.0459 
## R^2 (unadjusted):        R^2 = 0.7528</code></pre>
<p><img src="lmGC_files/figure-html/unnamed-chunk-14-1.png" width="528" /></p>
<p>The linear fit is graphed, but there is also a “loess” curve, a smooth curve that does not make much assumption about what kind of relationship produced the data in question. Surrounding the loess curve is a 95%-confidence band: based on the data we are pretty sure that the “real” relationship between <strong>wt</strong> and <strong>mpg</strong> is some function with a graph that lies within the band.</p>
<p>Now it is highly unlikely that our linear model gives the “real” relationship, but notice that the line stays within the 95%-confidence band. This means that it’s not such a bad idea to use the line to predict fuel efficiency from weight, for the range of weights for which we have data. The line does wander near the edge of the band for the higher weights, though, so we might employ extra caution there: common sense says, after all, that fuel efficiency should “level out” at very high weights, rather than follow the line.</p>
<p>On the other hand, consider a check on a linear model for the relationship between <strong>volume</strong> (number of bikes on the trail) and <strong>avgtemp</strong> (average temperature for the day) in the <code>RailTrail</code> data frame:</p>
<pre class="r"><code>lmGC(volume~avgtemp,data=RailTrail,check=TRUE)</code></pre>
<pre><code>## 
##  Linear Regression
## 
## Correlation coefficient r =  0.4269 
## 
## Equation of Regression Line:
## 
##   volume = 99.6023 + 4.802 * avgtemp 
## 
## Residual Standard Error: s   = 115.9202 
## R^2 (unadjusted):        R^2 = 0.1822</code></pre>
<p><img src="lmGC_files/figure-html/unnamed-chunk-15-1.png" width="528" /></p>
<p>Note that the regression line wanders a bit outside the band, so a linear fit probably is not quite adequate–especially for days with higher temperatures, when people may forsake bicyle trials for other warm-weather activities such as swimming. At very high temperatures outside the range for which we have data, <strong>volume</strong> should be low, so the “real” relationship is probably quite curvilinear. Perhaps we should learn how to fit something other than a straight line to data!</p>
</div>



<!-- bizible -->
<script type="text/javascript" src="//cdn.bizible.com/scripts/bizible.js" async=""></script>


<!-- disqus -->
<!--  <div id="disqus_thread" style="margin-top: 45px;"></div>
    <script type="text/javascript">
        /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
        var disqus_shortname = 'rmarkdown'; // required: replace example with your forum shortname

        /* * * DON'T EDIT BELOW THIS LINE * * */
        (function() {
            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
            dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
            (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
        })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
    <a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>

-->


</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
$(document).ready(function () {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
});

</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
