<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />




<title>Using qnorm()</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cosmo.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<link href="site_libs/font-awesome-4.5.0/css/font-awesome.min.css" rel="stylesheet" />

<style type="text/css">code{white-space: pre;}</style>
<link rel="stylesheet"
      href="site_libs/highlight/textmate.css"
      type="text/css" />
<script src="site_libs/highlight/highlight.js"></script>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs && document.readyState && document.readyState === "complete") {
   window.setTimeout(function() {
      hljs.initHighlighting();
   }, 0);
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>

<link rel="stylesheet" href="styles.css" type="text/css" />

</head>

<body>

<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
  height: auto;
}
.tabbed-pane {
  padding-top: 12px;
}
button.code-folding-btn:focus {
  outline: none;
}
</style>

<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 51px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 56px;
  margin-top: -56px;
}

.section h2 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h3 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h4 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h5 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h6 {
  padding-top: 56px;
  margin-top: -56px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>


<div class="container-fluid main-container">

<!-- tabsets -->
<script src="site_libs/navigation-1.0/tabsets.js"></script>
<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});
</script>

<!-- code folding -->




<script>
$(document).ready(function ()  {

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\/?&!#<>]/g, '').replace(/\s/g, '_').toLowerCase();
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = false;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.9em;
  padding-left: 5px;
}

.tocify .list-group-item {
  border-radius: 0px;
}

.tocify-subheader {
  display: inline;
}
.tocify-subheader .tocify-item {
  font-size: 0.95em;
  padding-left: 10px;
}

</style>

<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row-fluid">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-inverse  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">tigerstats</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li>
  <a href="about.html">About</a>
</li>
<li>
  <a href="instructorNotes.html">Instructors</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Vignettes
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li class="dropdown-header">Outlines</li>
    <li>
      <a href="R_Descriptive.html">Descriptive Outline</a>
    </li>
    <li>
      <a href="R_Inferential.html">Inferential Outline</a>
    </li>
    <li class="dropdown-header">Graphics</li>
    <li>
      <a href="barchartGC.html">Bar Charts</a>
    </li>
    <li>
      <a href="bwplot.html">Box-and-Whisker Plots</a>
    </li>
    <li>
      <a href="densityplot.html">Density Plots</a>
    </li>
    <li>
      <a href="histogram.html">Histograms</a>
    </li>
    <li class="dropdown-header">Numerical Summaries</li>
    <li>
      <a href="favstats.html">Mosaic's Favstats</a>
    </li>
    <li>
      <a href="xtabs.html">Cross-tables and Percentages</a>
    </li>
    <li class="dropdown-header">Linear Mpdels</li>
    <li>
      <a href="lmGC.html">lmGC</a>
    </li>
    <li>
      <a href="polyfitGC.html">polyfitGC</a>
    </li>
    <li class="dropdown-header">Probability</li>
    <li>
      <a href="pbinomGC.html">pbinomGC</a>
    </li>
    <li>
      <a href="pnormGC.html">pnormGC</a>
    </li>
    <li>
      <a href="qnorm.html">qnorm</a>
    </li>
    <li>
      <a href="qnormGC.html">qnormGC</a>
    </li>
    <li class="dropdown-header">Inferential Procedures</li>
    <li>
      <a href="binomtestGC.html">binomtestGC</a>
    </li>
    <li>
      <a href="proptestGC.html">proptestGC</a>
    </li>
    <li>
      <a href="chisqtestGC.html">The Chi-Square Test</a>
    </li>
    <li>
      <a href="ttestGC.html">The t-Test</a>
    </li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="https://github.com/homerhanumat/tigerstats">
    <span class="fa fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">



<h1 class="title toc-ignore">Using qnorm()</h1>

</div>


<div id="comparison-of-qnorm-with-pnormgc" class="section level1">
<h1>Comparison of <code>qnorm()</code> with <code>pnormGC()</code></h1>
<p>The function <code>pnorm()</code> in regular <code>R</code>, as well as the function <code>pnormGC() in the</code>tigerstats` package, compute probabilities from known bounding values. For example, suppose that <span class="math inline">\(X\)</span> is a normally distributed random variable with mean 70 and standard deviation 3, and that you want to know:</p>
<p><span class="math display">\[P(X &lt; 72).\]</span></p>
<p>Then you <em>know</em> the boundary value 72, but you don’t know the probability: the area under the normal density curve before 72. Functions like <code>pnormGC()</code> aim to give you that area–that probability:</p>
<pre class="r"><code>pnormGC(72, region=&quot;below&quot;, mean=70,
        sd=3,graph=TRUE)</code></pre>
<p><img src="qnorm_files/figure-html/qnormtut72-1.png" width="528" /></p>
<pre><code>## [1] 0.7475075</code></pre>
<p>The function <code>qnorm()</code>, which comes standard with R, aims to do the opposite: given an area, find the boundary value that determines this area.</p>
<p>For example, suppose you want to find that 85th percentile of a normal distribution whose mean is 70 and whose standard deviation is 3. Then you ask for:</p>
<pre class="r"><code>qnorm(0.85,mean=70,sd=3)</code></pre>
<pre><code>## [1] 73.1093</code></pre>
<p>The value 73.1093 is indeed the 85th percentile, in the sense that 85% of the values in a population that is normally distributed with mean 70 and standard deviation 3 will lie below 73.1093. In other words, if you were to pick a random member <span class="math inline">\(X\)</span> from such a population, then</p>
<p><span class="math display">\[P(X &lt; 73.1093) = 0.85\]</span>.</p>
<p>You can check that this is correct by plugging 73.1093 into <code>pnormGC()</code>:</p>
<pre class="r"><code>pnormGC(73.1093,region=&quot;below&quot;,mean=70,
        sd=3,graph=TRUE)</code></pre>
<p><img src="qnorm_files/figure-html/qnormtut73-1.png" width="528" /></p>
<pre><code>## [1] 0.85</code></pre>
<p>Sure enough, the area under the curve before 73.1093 is 0.85.</p>
</div>
<div id="a-few-more-examples" class="section level1">
<h1>A Few More Examples</h1>
<div id="making-the-top-ten-percent-an-area-above" class="section level2">
<h2>Making the Top Ten Percent (An Area Above)</h2>
<blockquote>
<p>Suppose that SAT scores are normally distributed, and that the mean SAT score is 1000, and the standard deviation of all SAT scores is 100. <em>How high must you score so that only 10% of the population scores higher than you?</em></p>
</blockquote>
<p>Here’s the solution. If 10% score higher than you, then 90% score lower. So just call <code>qnorm()</code> with 0.90 as the boundary value:</p>
<pre class="r"><code>qnorm(0.90,mean=1000,sd=100)</code></pre>
<pre><code>## [1] 1128.155</code></pre>
<p>In other words, the 90th percentile of SAT scores is around 1128.</p>
<p><strong>Note</strong>: <code>qnorm()</code> deals by default with areas <em>below</em> the given boundary value. If we had asked for:</p>
<pre class="r"><code>qnorm(0.10,mean=1000,sd=100)</code></pre>
<p>then we would have got only the 10th percentile of the SAT scores, not the desired 90th percentile. If you would like to input 0.10 directly, then you can do so provided that you fiddle with the <code>lower.tail</code> argument:</p>
<pre class="r"><code>qnorm(0.10,mean=1000,sd=100,
      lower.tail=FALSE)</code></pre>
<pre><code>## [1] 1128.155</code></pre>
<p>But really it seems easier just to do the math:</p>
<p><span class="math inline">\(1 - 0.10 = 0.90.\)</span></p>
</div>
<div id="an-area-between" class="section level2">
<h2>An Area Between</h2>
<blockquote>
<p>Find a positive number <span class="math inline">\(z\)</span> so that the area under the standard normal curve between <span class="math inline">\(-z\)</span> and <span class="math inline">\(z\)</span> is 0.95.</p>
</blockquote>
<p>Here’s the solution. If 95% of the area lies between <span class="math inline">\(-z\)</span> and <span class="math inline">\(z\)</span>, then 5% of the area must lie outside of this range. since normal curves are symmetric, half of this amount–2.5%–must lie before <span class="math inline">\(-z\)</span>. Then the area under the curve before <span class="math inline">\(z\)</span> must be:</p>
<p><span class="math display">\[0.025+0.95=0.975.\]</span></p>
<p>Hence the number <span class="math inline">\(z\)</span> is actually the 97.5th percentile of the standard normal distribution, and we can find it as follows:</p>
<pre class="r"><code>qnorm(0.975,mean=0,sd=1)</code></pre>
<pre><code>## [1] 1.959964</code></pre>
<p>So <span class="math inline">\(z\)</span> is about 1.96. We can check this result graphically as follows:</p>
<pre class="r"><code>pnormGC(c(-1.96,1.96),region=&quot;between&quot;,mean=0,
        sd=1,graph=TRUE)</code></pre>
<p><img src="qnorm_files/figure-html/qnormtutbetween-1.png" width="528" /></p>
<pre><code>## [1] 0.9500042</code></pre>
</div>
</div>



<!-- bizible -->
<script type="text/javascript" src="//cdn.bizible.com/scripts/bizible.js" async=""></script>


<!-- disqus -->
<!--  <div id="disqus_thread" style="margin-top: 45px;"></div>
    <script type="text/javascript">
        /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
        var disqus_shortname = 'rmarkdown'; // required: replace example with your forum shortname

        /* * * DON'T EDIT BELOW THIS LINE * * */
        (function() {
            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
            dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
            (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
        })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
    <a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>

-->


</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
$(document).ready(function () {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
});

</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
